const comics = [
  {
    _id: "1",
    name: "The Amazing Spider-Man (2018)",
    image: "/images/airpods.jpg",
    description: "Written by: Nick Spencer , Drawn By: Various Artists",
    publisher: "Marvel",
    category: "Ongoing Series",
    avgPrice: 3.99,
    currentIssue: 54,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Batman (2016)",
    image: "/images/airpods.jpg",
    description: "Written by: James Tynion IV , Drawn By: Various Artists",
    publisher: "DC",
    category: "Ongoing Series",
    avgPrice: 3.99,
    currentIssue: 104,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "Batman/Catwoman",
    image: "/images/airpods.jpg",
    description: "Written by: Tom King , Drawn By: Clay Mann",
    publisher: "DC",
    category: "Limited Series",
    avgPrice: 4.99,
    currentIssue: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Action Comics (2016)",
    image: "/images/airpods.jpg",
    description: "Written by: Brian Michael Bendis , Drawn By: Various Artists",
    publisher: "DC",
    category: "Ongoing Series",
    avgPrice: 3.99,
    currentIssue: 1027,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Star Wars (2020)",
    image: "/images/airpods.jpg",
    description: "Written by: Charles Soule , Drawn By: Various Artists",
    publisher: "Marvel",
    category: "Ongoing Series",
    avgPrice: 3.99,
    currentIssue: 9,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "Dark Nights: Death Metal (2020)",
    image: "/images/airpods.jpg",
    description: "Written by: Scott Snyder , Drawn By: Greg Capullo",
    publisher: "DC",
    category: "Limited Series",
    avgPrice: 4.99,
    currentIssue: 5,
    rating: 4.5,
    numReviews: 12,
  },
];

export default comics;
